apiVersion: apps/v1
kind: Deployment
metadata:
  name: hfgrrde
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hfgrrde
  template:
    metadata:
      labels:
        app: hfgrrde
    spec:
      containers:
      - image: okteto.dev/hfgrrde:latest
        name: hfgrrde
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "27213ba3-01af-4006-bb39-9bb5fe259d4c"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "27213ba3-01af-4006-bb39-9bb5fe259d4c"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
